// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Application    string
	GooseDBVersion string
}{
	Application:    "application",
	GooseDBVersion: "goose_db_version",
}
